---
- name: Configure HPC Environment for OpenFlightHPC Compute
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - meta
    - upstream
    - ssh
    - slurm
    - nfs
    - flightenv
    - flightenv-bootstrap
    - flightweb
    - alces
    - user
