- name: Install packages
  yum:
    name:
      "{{ all_packages }}"
    state: present
    disable_gpg_check: yes
  vars:
    generic_list:
      - flight-runway
      - flight-starter
      - flight-env
      - flight-desktop
      - vte-profile
    all_packages: "{{ generic_list + ['vte', 'pdsh', 'pdsh-mod-genders'] if ansible_distribution_major_version == '7' else generic_list }}"

- name: Set cluster name
  command: "/opt/flight/bin/flight config set cluster.name {{ cluster_name }}"

- name: Create genders file
  template: src=genders dest=/opt/flight/etc/genders

- name: Configure global software environment location
  template: src=config.yml dest=/opt/flight/opt/flight-env/etc/config.yml

- name: Configure Singularity environment to work for users
  sysctl:
    name: user.max_user_namespaces
    value: '100'
    sysctl_set: yes
    state: present
    reload: yes

