- name: Install packages
  yum:
    name:
      - flight-runway
      - flight-starter
      - flight-env
      - vte
      - vte-profile
    state: present
    disable_gpg_check: yes

- name: Set cluster name
  command: "/opt/flight/bin/flight config set cluster.name {{ cluster_name }}"

