- name: Prepare gnome desktop
  command: "/opt/flight/bin/flight desktop prepare gnome"
  when:
    - flightenv_prepare
    - "'gateway' in group_names"

- name: Prepare xterm desktop
  command: "/opt/flight/bin/flight desktop prepare xterm"
  when:
    - flightenv_prepare
    - "'gateway' in group_names"

- name: Add gridware binary support
  file:
    path: "/opt/apps/flight/env/u"
    state: directory
    mode: 1777
  when:
    - flightenv_prepare
    - "'gateway' in group_names"

- name: Prepare global software environments
  command: "/opt/flight/bin/flight env create --global {{ item }}@global"
  with_items: "{{ flightenv_prepare_software }}"
  when:
    - flightenv_prepare
    - "'gateway' in group_names"

- name: Tidy global preparations
  command: "/opt/flight/bin/flight env purge --yes {{ item }}@global"
  with_items: "{{ flightenv_prepare_software }}"
  when:
    - flightenv_prepare
    - "'gateway' in group_names"

- name: Prepare local software environments
  command: "/opt/flight/bin/flight env create {{ item }}"
  become: true
  become_user: "{{ flightenv_prepare_user }}"
  with_items: "{{ flightenv_prepare_software }}"
  when:
    - flightenv_prepare
    - "'gateway' in group_names"

- name: Tidy local preparations
  command: "/opt/flight/bin/flight env purge --yes {{ item }}"
  become: true
  become_user: "{{ flightenv_prepare_user }}"
  with_items: "{{ flightenv_prepare_software }}"
  when:
    - flightenv_prepare
    - "'gateway' in group_names"
