- name: Prepare gnome desktop
  command: "/opt/flight/bin/flight desktop prepare gnome"
  when:
    - flightenv-prepare
    - "'gateway' in group_names"

- name: Prepare xterm desktop
  command: "/opt/flight/bin/flight desktop prepare xterm"
  when:
    - flightenv-prepare
    - "'gateway' in group_names"

- name: Prepare global software environments
  command: "/opt/flight/bin/flight env create --global {{ item }}@global"
  with_items: "{{ flightenv-prepare_software }}"
  when:
    - flightenv-prepare
    - "'gateway' in group_names"

- name: Tidy global preparations
  command: "/opt/flight/bin/flight env purge --yes {{ item }}@global"
  with_items: "{{ flightenv-prepare_software }}"
  when:
    - flightenv-prepare
    - "'gateway' in group_names"

- name: Prepare local software environments
  command: "/opt/flight/bin/flight env create {{ item }}"
  become: true
  become_user: "{{ flightenv-prepare_user }}"
  with_items: "{{ flightenv-prepare_software }}"
  when:
    - flightenv-prepare
    - "'gateway' in group_names"

- name: Tidy local preparations
  command: "/opt/flight/bin/flight env purge --yes {{ item }}"
  become: true
  become_user: "{{ flightenv-prepare_user }}"
  with_items: "{{ flightenv-prepare_software }}"
  when:
    - flightenv-prepare
    - "'gateway' in group_names"
