- name: Prepare gnome desktop
  command: "/opt/flight/bin/flight desktop prepare gnome"

- name: Prepare xterm desktop
  command: "/opt/flight/bin/flight desktop prepare xterm"

- name: Prepare global software environments
  command: "/opt/flight/bin/flight env create --global {{ item }}@global"
  with_items: "{{ flightenv-prepare_software }}"

- name: Tidy global preparations
  command: "/opt/flight/bin/flight env purge --yes {{ item }}@global"
  with_items: "{{ flightenv-prepare_software }}"

- name: Prepare local software environments
  command: "/opt/flight/bin/flight env create {{ item }}"
  become: true
  become_user: "{{ flightenv-prepare_user }}"
  with_items: "{{ flightenv-prepare_software }}"

- name: Tidy local preparations
  command: "/opt/flight/bin/flight env purge --yes {{ item }}"
  become: true
  become_user: "{{ flightenv-prepare_user }}"
  with_items: "{{ flightenv-prepare_software }}"
