- name: Set SSH Alive Interval
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?ClientAliveInterval
    line: ClientAliveInterval 60

- name: Set SSH Alive Count
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?ClientAliveCountMax
    line: ClientAliveCountMax 2

- name: Restart SSHD
  service: "name=sshd state=restarted"

