- name: Waiting for nodes to be reachable
  wait_for_connection:
    sleep: 10
    timeout: 600

- name: Install EPEL Repo
  yum: name=epel-release state=present

- name: Add OpenFlight SLURM Repo
  yum_repository:
    name: openflight-slurm
    description: OpenFlight SLURM Repo
    state: present
    baseurl: https://openflighthpc-compute.s3-eu-west-2.amazonaws.com/slurm/

- name: Add OpenFlight Release Repo
  yum: name=https://openflighthpc.s3-eu-west-1.amazonaws.com/repos/openflight/x86_64/openflighthpc-release-1-1.noarch.rpm state=present

