- name: Install SLURM controller packages
  yum:
    name: 
      "{{ all_packages }}"
    state: present
    disable_gpg_check: yes
  vars:
    generic_list:
      - mariadb
      - mariadb-test
      - mariadb-embedded
      - flight-slurm-slurmctld
      - flight-slurm-slurmdbd
    all_packages: "{{ generic_list + ['mariadb-libs', 'mariadb-bench'] if ansible_distribution_major_version == '7' else generic_list }}"

- name: Turn on MariaDB
  service: name=mariadb state=started enabled=yes

- name: Prepare Accounting DB
  command: "{{ item }}"
  with_items:
    - mysql -uroot -e "create user 'slurm'@'localhost' identified by '';"
    - mysql -uroot -e "grant all on slurm_acct_db.* TO 'slurm'@'localhost';"
    - mysql -uroot -e "CREATE DATABASE slurm_acct_db;"

- name: Install slurmdbd.conf
  template:
    src: slurmdbd.conf
    dest: /opt/flight/opt/slurm/etc/slurmdbd.conf
    owner: nobody
    group: nobody
    mode: '0600'

- name: Create spool directory
  file:
    path: /opt/flight/opt/slurm/var/spool/slurm.state
    state: directory
    owner: nobody
    group: nobody

- name: Turn on SlurmDBD
  service: name=flight-slurmdbd state=started enabled=yes

- name: Turn on SLURM controller daemon
  service: name=flight-slurmctld state=started enabled=yes
