- name: Install NFS utils
  yum: name=nfs-utils state=present

- name: Create export directories
  file:
    path: "{{ item.value.export }}"
    state: directory
    mode: 0775
  with_dict: "{{ nfs_shares }}"

- name: Create export file
  template: src=exports dest=/etc/exports

- name: Create fstab file
  lineinfile:
    path: /etc/fstab
    line: "{% if item.value.export != item.value.mountpoint %}{{ item.value.export }}    {{ item.value.mountpoint }}    none    defaults,bind    0 0{% endif %}"
    state: present
  with_dict: "{{ nfs_shares }}"

- name: Create mount directories
  file:
    path: "{{ item.value.mountpoint }}"
    state: directory
    mode: 0775
  with_dict: "{{ nfs_shares }}"

- name: Start NFS server service
  service: "name=nfs-server state=started enabled=yes"
  when: ansible_distribution_major_version == '8'

- name: Start NFS service
  service: "name=nfs state=started enabled=yes"
  when: ansible_distribution_major_version == '7'

- name: Export mounts
  command: exportfs -va

- name: Mount NFS exports
  command: mount -a
  args:
    warn: no
